"""empty message

Revision ID: 741c4c2f474f
Revises: 
Create Date: 2023-06-21 17:10:01.780556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741c4c2f474f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('abbreviation')
    )
    op.create_table('rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_abb', sa.String(length=5), nullable=True),
    sa.Column('course', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['currency_abb'], ['currency.abbreviation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_id'), 'rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rates_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_table('currency')
    # ### end Alembic commands ###
